[package]
name = "StarkBank"
version = "0.1.0"
license = "MIT"
authors = []
keywords = []
description = "View in an interactive way your borrowing positions"

repository = "https://github.com/@GustaveCharles/StarkBank"

[[target.starknet-contract]]
sierra = true
casm = true

[dependencies]
# TODO: Make Starknet version configurable
starknet = ">=2.1.0"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.4.0" }


[tool.snforge]
exit_first = false
